"""add clusters table and user cluster_id

Revision ID: 134a7c958847
Revises: c194b2b558d5
Create Date: 2026-09-14 12:17:46.162225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134a7c958847'
down_revision: Union[str, None] = 'c194b2b558d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('craft_type', sa.String(length=50), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('member_craft_names', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['craft_type'], ['craft_types.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_craft_type'), 'clusters', ['craft_type'], unique=False)
    op.create_index(op.f('ix_clusters_state_code'), 'clusters', ['state_code'], unique=False)
    op.add_column('users', sa.Column('cluster_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cluster_id')
    op.drop_index(op.f('ix_clusters_state_code'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_craft_type'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
