"""add ondc marketplace_listings and integration_events

Revision ID: 497fd9961982
Revises: eb2097791550
Create Date: 2026-09-05 16:38:59.421683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497fd9961982'
down_revision: Union[str, None] = 'eb2097791550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_message_id'), 'integration_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_integration_events_transaction_id'), 'integration_events', ['transaction_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace', sa.String(length=30), nullable=False),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('external_item_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_listing_id'), 'marketplace_listings', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_listings_listing_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_integration_events_transaction_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_message_id'), table_name='integration_events')
    op.drop_table('integration_events')
    # ### end Alembic commands ###
