"""add live location fields to users

Revision ID: 65c3c993ebe7
Revises: d9165a717e0b
Create Date: 2026-09-11 09:18:53.964233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c3c993ebe7'
down_revision: Union[str, None] = 'd9165a717e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_sharing_location', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_sharing_location')
    op.drop_column('users', 'location_updated_at')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
