"""add brightness and blur_score to product_images

Revision ID: d9165a717e0b
Revises: fe250700b5e0
Create Date: 2026-09-06 22:51:30.838343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9165a717e0b'
down_revision: Union[str, None] = 'fe250700b5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('brightness', sa.Float(), nullable=True))
    op.add_column('product_images', sa.Column('blur_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'blur_score')
    op.drop_column('product_images', 'brightness')
    # ### end Alembic commands ###
