"""initial schema

Revision ID: eb2097791550
Revises: 
Create Date: 2026-09-04 17:41:44.197718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2097791550'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_phone_number'), 'otp_verifications', ['phone_number'], unique=False)
    op.create_table('states',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('supported_languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('name_native', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('craft_types', sa.JSON(), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gem_seller_id', sa.String(length=100), nullable=True),
    sa.Column('ondc_subscriber_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('districts',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_districts_state_code'), 'districts', ['state_code'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_user_id', sa.String(length=36), nullable=False),
    sa.Column('seller_user_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_address', sa.JSON(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_status', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_user_id'), 'orders', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_user_id'), 'orders', ['seller_user_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('enhanced_url', sa.String(length=500), nullable=True),
    sa.Column('bg_removed_url', sa.String(length=500), nullable=True),
    sa.Column('aspect_ratio_1x1_url', sa.String(length=500), nullable=True),
    sa.Column('aspect_ratio_4x5_url', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_blurry', sa.Boolean(), nullable=False),
    sa.Column('is_too_dark', sa.Boolean(), nullable=False),
    sa.Column('is_overexposed', sa.Boolean(), nullable=False),
    sa.Column('quality_issues', sa.JSON(), nullable=True),
    sa.Column('enhancement_status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_draft_id'), 'product_images', ['draft_id'], unique=False)
    op.create_index(op.f('ix_product_images_user_id'), 'product_images', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.String(length=2000), nullable=False),
    sa.Column('description_hi', sa.String(length=2000), nullable=False),
    sa.Column('craft_type', sa.String(length=50), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['product_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_product_images_user_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_draft_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_orders_seller_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_districts_state_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('supported_languages')
    op.drop_table('states')
    op.drop_index(op.f('ix_otp_verifications_phone_number'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_table('craft_types')
    # ### end Alembic commands ###
