"""add transparent_url and processing_meta to product_images

Revision ID: fe250700b5e0
Revises: 6ce335b20a88
Create Date: 2026-09-06 22:34:58.915566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe250700b5e0'
down_revision: Union[str, None] = '6ce335b20a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('transparent_url', sa.String(length=500), nullable=True))
    op.add_column('product_images', sa.Column('processing_meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'processing_meta')
    op.drop_column('product_images', 'transparent_url')
    # ### end Alembic commands ###
